### ISSUE TITLE
Backlog: Implement a way to set cells in the buffer without printing to the screen

### ISSUE THREAD

**Issue by imdaveho** [imdaveho/tuitty-core#11]
**Problem to Solve**
With `prints` and `printf`, we not only update the internal buffer, we also write to `stdout`. This creates a moment when the cursor hops to the end of the printed content and leaves it up to the implementer to hop the cursor back to where it was. This little "flash" is not great, as it leaks out implementation details to the end user of the application.

**Proposal**
At one point we toyed around with having the screen redraw the contents of the buffer every time. This proved to be quite inefficient (as flushes are expensive). However, on thing we can do, is to make `set_cell` public and to make `render` into another `Signal`. This way, there might be moments when you want to update the internal buffer, and when ready, render it on the screen at once, to prevent the cursor from hopping all around.

The goal is to render the output to the screen without the cursor going crazy. The implementation can vary. The above is the initial thought that can be tested.

**Tasks**
* [ ] expose `set_cell` in `cells.rs` publically
* [ ] create a `Render` Signal
* [ ] experiment and gauge performance

**Comment by imdaveho** [comment]
completed in https://github.com/imdaveho/tuitty-rs/commit/09f20f70ab1bda5087d6663e878d5e8a390f65a3
